=== SabdaAlamsyah/Tugas-Praktikum-XSD-XML-Modul/tugas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Bidang">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alamat"/>
                <xs:element ref="alamatpenerima"/>
                <xs:element ref="alamatpengirim"/>
                <xs:element ref="email"/>
                <xs:element ref="harga"/>
                <xs:element ref="jeniskelamin"/>
                <xs:element ref="jenispengiriman"/>
                <xs:element ref="kode"/>
                <xs:element ref="kontak"/>
                <xs:element ref="nama"/>
                <xs:element ref="tanggal"/>
            </xs:choice>
            <xs:attribute name="Data" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="alamat" type="xs:string"/>
    <xs:element name="alamatpenerima" type="xs:NCName"/>
    <xs:element name="alamatpengirim" type="xs:NCName"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="harga" type="xs:string"/>
    <xs:element name="jeniskelamin" type="xs:string"/>
    <xs:element name="jenispengiriman" type="xs:NCName"/>
    <xs:element name="kode" type="xs:integer"/>
    <xs:element name="kontak" type="xs:integer"/>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="tanggal" type="xs:NMTOKEN"/>
</xs:schema>

=== SabdaAlamsyah/Tugas-Praktikum-XSD-XML-Modul/Tugas.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bidang jasa="JNE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tugas.xsd">
	<nama>Sabda Alamsyah</nama>
	<kode>1</kode>
	<tanggal>06-04-2017</tanggal>
	<jenispengiriman>yes</jenispengiriman>
	<harga>RP: 10000</harga>
	<jeniskelamin>Laki Laki</jeniskelamin>
	<email>alamsyahsabda1832@gmail.com</email>
	<kontak>081214419139</kontak>
	<alamatpengirim nama="Bandung"></alamatpengirim>
	<alamatpenerima nama="Tasikmalaya">
		<alamat>jl. BKR no.54 Tasikmalaya</alamat>
	</alamatpenerima>
	
	<nama>Diana Satima</nama>
	<kode>2</kode>
	<tanggal>12-04-2017</tanggal>
	<jenispengiriman>ok</jenispengiriman>
	<harga>RP: 150000</harga>
	<jeniskelamin>Perempuan</jeniskelamin>
	<email>dianasatima@gmail.com</email>
	<kontak>082321485543</kontak>
	<alamatpengirim nama="Banjar"></alamatpengirim>
	<alamatpenerima nama="Pangandaran">
		<alamat>jl. pangandarana no.67</alamat>
	</alamatpenerima>
	
	<nama>Indah Rahma</nama>
	<kode>3</kode>
	<tanggal>15-04-2017</tanggal>
	<jenispengiriman>ok</jenispengiriman>
	<harga>RP: 150000</harga>
	<jeniskelamin>Perempuan</jeniskelamin>
	<email>indah@gmail.com</email>
	<kontak>083321945621</kontak>
	<alamatpengirim nama="Cirebon"></alamatpengirim>
	<alamatpenerima nama="sukabumi">
		<alamat>jl. palangkritis no.123</alamat>
	</alamatpenerima>
	
	<nama>Yusri Rizal</nama>
	<kode>4</kode>
	<tanggal>19-04-2017</tanggal>
	<jenispengiriman>yes</jenispengiriman>
	<harga>RP: 10000</harga>
	<jeniskelamin>Laki Laki</jeniskelamin>
	<email>yusririzal18@gmail.com</email>
	<kontak>0812566543218</kontak>
	<alamatpengirim nama="Cianjur"></alamatpengirim>
	<alamatpenerima nama="sukabumi">
		<alamat>jl. pahlawan no.2</alamat>
	</alamatpenerima>
	
	<nama>Tias</nama>
	<kode>5</kode>
	<tanggal>29-04-2017</tanggal>
	<jenispengiriman>yes</jenispengiriman>
	<harga>RP: 10000</harga>
	<jeniskelamin>Laki Laki</jeniskelamin>
	<email>tiasmaaulana@gmail.com</email>
	<kontak>085222485623</kontak>
	<alamatpengirim nama="Tanggerang"></alamatpengirim>
	<alamatpenerima nama="Bandung">
		<alamat>jl. Bandung no.2</alamat>
   </alamatpenerima>
</Bidang>
